### ISSUE TITLE
Jumper choice

### ISSUE THREAD

**Issue by sconklin** [dkozel/noisesource-psu#3]
This is a matter of opinion, but I'd use a single  SolderJumper_3 type instead of the two jumpers you have for TPS_EN. It makes it harder to misconfigure the jumpers and short the CBUS2 output to 5V1.

**Comment by dkozel** [comment]
Ah! Yes. That makes a lot of sense. I ended up with the two separate jumpers because the idea to have them came up fairly late and I originally had each part of the jumper next to each IC. I was also imagining the use of a 0 Ohm resistor to do the bridging, but that's overkill for a small prototype run.

**Comment by daveb377** [comment]
0 ohm resistors are pretty cheap

**Comment by dkozel** [comment]
Resolved by moving to a single three pad jumper and footprint.
